### ISSUE TITLE
Simple form for inserting a PoliticalEntity object 

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catalog-politic-aggregator#1]
The aggregator should be able to provide to a regular user a simple form.
The form should contain all the fields necessary for filling in the details of the PoliticalEntity object.
The form should contain 5 tabs for each part of the profile:
- ProfilPersonal
- Traseism
- ProfilPolitic
- Avere
- Dna

The technology used should be Spring MVC.

**Comment by Deviad** [comment]
Hello Radu, 
I don't really get the big picture. Last time I worked on a Python tool that did this automatically. 
In this case, a hypothetical user should fill the fields related to a given politician. 
Who are our users? Who is going to do this? 
Is there any UX ready for this? 
Should the UI be made with Thymeleaf or can we do it with Javascript as well? 
I have experience both with Spring Boot and React.
I would like to accomplish this task @RaduCStefanescu

**Comment by RaduCStefanescu** [comment]
In progress @Deviad
