### ISSUE TITLE
Export JSON files to Amazon S3 bucket

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catalog-politic-aggregator#4]
The profiles saved in MongoDB as JSONs should be exported to Amazon S3 bucket.

**Comment by boneacsu** [comment]
Hey Radu, I would like to help with this one, is there any arch constraints or any arch overview for that matter?

**Comment by RaduCStefanescu** [comment]
No architecture constraints on exporting files to S3 bucket. 
Just take into consideration that the process will need configurable (application.yml I mean) credentials for exporting to Amazon S3.

**Comment by RaduCStefanescu** [comment]
In progress @boneacsu

**Comment by boneacsu** [comment]
I'll need couple of details. I would really appreciate some answers, even short : 

1. Should it be just a module in the project (just drop in the proj with an exposed api would suffice?)
2. Is it a microservice with REST or plain java API? Maybe Boot service?
4. Docker?
5. Does the API receive a doc id, a list or some kind of selector to stream the docs from one point(mongo instance) to another (s3)?
6. It will pretty much work like a scheduled task(snapshot) or should be event based? If so, did we thought and dropped kafka connect as a mean for this?
7. Any logs, metrics or audit for the copy operation?
8. Test env details? 
9. Do we have, yet, a build system in place?

**Comment by Owlree** [comment]
Hello,

I did acknowledge you question. However, I will close this issue for now, as the main focus for the team is to get the React web app MVP done by October 10. The architecture of the data pipeline will need to be rediscussed once the MVP is out and we are gathering feedback both from users and researchers adding data to our platform. 

We have open React issues [here](https://github.com/code4romania/catalog-politic/issues), if you would like to take a look.

**Comment by RaduCStefanescu** [comment]
@boneacsu thanks for taking interest in this issue. I'll try to briefly respond to your questions:
1. Yes, module in the project. The way I see it, we should define an interface for persisting the JSON files to storage. One of the implementations deals with persisting to Amazon S3, maybe another implementation deals with persisting to local storage for local development purposes.
2. No, not microservice, have a look at answer 1
3. Yes, I want the solution to run in a Docker container, but that should be handled in a different issue.
4. No, the way I see it is that we aggregate the information and produce the JSON files and then, transactionally, we write these files to a database (Mongo/Dynamo - right now we are actually considering to use Dynamo, so the database layer should be as thin as possible) and persist to S3 storage.
5. The aggregator will work in both system modes - scheduled and per request. I don't see yet the reason for using Kafka Connect, as we are going to run everything on AWS infrastructure, so I would rely on AWS for reliability. If I am missing something here, let me know.
6. Logging would be great, the other are really really nice to have
7. Test environment is not yet setup, but most definitely would be on AWS.
8. Github actions will take care of the deployment. If I did not answer your question please let me know.

**Comment by boneacsu** [comment]
ok. Working on it
